# FILE_PATH = 'D:/Desktop/Fall_22_Academics/520_Intro to AI/Project_2/Data/'
FILE_PATH = '/Users/dhanur/Everything/Subjects/520_Intro_to_Artificial_Intelligence/Projects/Project_2/circle_of_life/The-Circle-of-Life/data/'
FILE_NAME = 'Agent_7_data.csv'

NUMBER_OF_GAMES = 30
NUMBER_OF_ARENAS = 100
FORCED_TERMINATION_THRESHOLD = 10000
SCARED_THRESHOLD = 3

# NUMBER_OF_GAMES = 1
# NUMBER_OF_ARENAS = 1
# FORCED_TERMINATION_THRESHOLD = 1000
# SCARED_THRESHOLD = 1

# NUMBER_OF_GAMES = 1
# NUMBER_OF_ARENAS = 1
# FORCED_TERMINATION_THRESHOLD = 10000
# SCARED_THRESHOLD = 3